/**
 * The seam that keeps the storage decision reversible.
 *
 * Today this is backed by index.json in the repo. If the portfolio ever
 * outgrows a whole-index read (docs/ARCHITECTURE.md §10 names the triggers),
 * a database implementation of this interface swaps in without touching a
 * single route or any UI code. Nothing outside this file may read index.json.
 */
import type { CustomerIndex, ExceptionFeed, IndexEntry } from '@cs/core';
import { getFile } from './github.ts';
import type { Env } from './env.ts';

export interface IndexProvider {
  getAll(): Promise<CustomerIndex>;
  getCustomer(slug: string): Promise<IndexEntry | null>;
  getExceptions(): Promise<ExceptionFeed>;
}

/**
 * Dashboards tolerate being a rebuild behind — the index is regenerated by CI
 * within about a minute of a write. Single-customer views do not use this path;
 * they read the underlying files directly and are always fresh.
 */
const TTL_SECONDS = 45;

interface CacheSlot<T> {
  value: T;
  fetchedAt: number;
}

export function fileIndexProvider(env: Env): IndexProvider {
  let indexSlot: CacheSlot<CustomerIndex> | null = null;
  let feedSlot: CacheSlot<ExceptionFeed> | null = null;

  const fresh = (slot: CacheSlot<unknown> | null): boolean =>
    slot !== null && Date.now() - slot.fetchedAt < TTL_SECONDS * 1000;

  async function readJson<T>(path: string, empty: T): Promise<T> {
    const file = await getFile(env, path);
    // A repo with no customers yet has no index. That is a legitimate empty
    // state, not an error the dashboard should blow up on.
    if (!file) return empty;
    return JSON.parse(file.text) as T;
  }

  const emptyIndex: CustomerIndex = {
    schema_version: 1,
    generated_at: new Date(0).toISOString(),
    as_of: '1970-01-01',
    totals: {
      customers: 0,
      by_band: { green: 0, amber: 0, red: 0 },
      arr_total: 0,
      arr_not_green: 0,
      exceptions_by_severity: { critical: 0, high: 0, medium: 0, low: 0 },
      open_commitments_past_due: 0,
      open_risks: 0,
    },
    customers: [],
  };

  return {
    async getAll() {
      if (fresh(indexSlot)) return indexSlot!.value;
      const value = await readJson<CustomerIndex>('index.json', emptyIndex);
      indexSlot = { value, fetchedAt: Date.now() };
      return value;
    },
    async getCustomer(slug) {
      const index = await this.getAll();
      return index.customers.find((c) => c.slug === slug) ?? null;
    },
    async getExceptions() {
      if (fresh(feedSlot)) return feedSlot!.value;
      const value = await readJson<ExceptionFeed>('exceptions.json', {
        schema_version: 1,
        generated_at: new Date(0).toISOString(),
        as_of: '1970-01-01',
        count: 0,
        exceptions: [],
      });
      feedSlot = { value, fetchedAt: Date.now() };
      return value;
    },
  };
}
